"""add ProductAdditionalInformation table

Revision ID: 571fcdececed
Revises: 6bbadd4d349b
Create Date: 2021-12-27 21:29:28.701898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571fcdececed'
down_revision = '6bbadd4d349b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productsAddInf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_quantity_add', sa.Integer(), nullable=True),
    sa.Column('product_quantity_returned', sa.Integer(), nullable=True),
    sa.Column('product_quantity_sale', sa.Integer(), nullable=True),
    sa.Column('product_quantity_waste', sa.Integer(), nullable=True),
    sa.Column('product_delivery_price_add', sa.Integer(), nullable=True),
    sa.Column('product_add_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('document', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productsAddInf')
    # ### end Alembic commands ###
