"""remove ProductAdditionalInformation table

Revision ID: 6efd8c24dbab
Revises: 571fcdececed
Create Date: 2021-12-27 21:48:04.454770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6efd8c24dbab'
down_revision = '571fcdececed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productsAddInf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productsAddInf',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"productsAddInf_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('product_quantity_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_quantity_returned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_quantity_sale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_quantity_waste', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_delivery_price_add', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_add_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='productsAddInf_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productsAddInf_pkey')
    )
    # ### end Alembic commands ###
